/**
 * Neutral internal warm-up message generation.
 *
 * SAFETY PROPERTIES:
 *  - NEVER uses a campaign template, campaign subject/body, or any lead data.
 *    The bodies here are a fixed, tiny, neutral set of plain-text sentences.
 *  - Every message carries a unique RFC 5322 Message-ID plus an X-Warmup-Job
 *    header so the IMAP poller can match an incoming message back to the exact
 *    job that produced it.
 *  - The headers contain NO credentials, no account password, no tokens, and no
 *    recipient address other than the enrolled pool mailbox itself.
 *  - Bodies are plain text and never contain a merge variable, so there is no
 *    way for prospect content to leak into a warm-up send.
 */

import { randomBytes } from "node:crypto";

/** Marker header the IMAP poller searches for. Never carries secrets. */
export const WARMUP_HEADER = "X-Leo-Warmup-Job";
export const WARMUP_VERSION_HEADER = "X-Leo-Warmup-Version";
export const WARMUP_VERSION = "1";

/** Neutral one-line subjects. No prospect names, no campaign copy. */
const SUBJECTS = [
  "Internal delivery check",
  "Warm-up message",
  "Mailbox health check",
  "Internal connectivity test",
  "Routing verification",
] as const;

const BODIES = [
  "This is an automated internal warm-up message sent between mailboxes owned by the same organisation. It contains no marketing content and no personal data.",
  "Automated internal message used to verify that outbound mail is routed and accepted between your own mailboxes. No action is required.",
  "This message exists only to confirm end-to-end mail flow between mailboxes under your control. It is not a campaign and carries no offer.",
  "Internal warm-up traffic. Generated by your own mail system to observe sending behaviour. Please disregard.",
  "A scheduled internal test message between your own mailboxes. No recipient data, no marketing content, no action needed.",
] as const;

/**
 * RFC 5322 msg-id. Deterministic in the job id so the IMAP poller can match on
 * the exact value we wrote, which is more reliable than matching a subject.
 */
export function buildWarmupMessageId(jobId: string, domain: string): string {
  const d = domain.replace(/[^a-zA-Z0-9.-]/g, "") || "localhost";
  return `<warmup-${jobId}@${d}>`;
}

/**
 * Build one warm-up message. `index` selects the neutral body so repeated sends
 * are not byte-identical (some providers penalise exact duplicates), but the
 * content is always drawn from the fixed neutral set -- never user content.
 */
export function buildWarmupContent(index: number, jobId: string): {
  subject: string;
  text: string;
  body: string;
} {
  const subject = SUBJECTS[index % SUBJECTS.length];
  const body = BODIES[index % BODIES.length];
  return {
    subject,
    body,
    text: `${body}\n\n-- \nWarm-up job: ${jobId}\nThis is automated internal traffic between your own mailboxes.\n`,
  };
}

/**
 * RFC 5322 message headers for a warm-up send. Returned as an array of
 * single-line "Name: value" strings.
 *
 * `jobId` is a cuid -- random, non-sequential, and contains nothing sensitive.
 */
export function buildWarmupHeaders(opts: {
  jobId: string;
  messageId: string;
  from: string;
  to: string;
  subject: string;
  nonce: string;
}): Array<[string, string]> {
  return [
    ["Message-ID", opts.messageId],
    ["From", opts.from],
    ["To", opts.to],
    ["Subject", opts.subject],
    [WARMUP_HEADER, opts.jobId],
    [WARMUP_VERSION_HEADER, WARMUP_VERSION],
    // Unique per send: defeats naive exact-duplicate collapsing downstream.
    ["X-Leo-Warmup-Nonce", opts.nonce],
    ["Auto-Submitted", "auto-generated"],
    ["Precedence", "bulk"],
    ["X-Leo-Auto-Response-Suppress", "All"],
  ];
}

/** Short random nonce for per-message uniqueness. */
export function warmupNonce(): string {
  return randomBytes(8).toString("hex");
}

/**
 * Extract a warm-up job id from raw IMAP headers.
 *
 * Parses LINE BY LINE rather than with a multiline regex. A regex with the `m`
 * flag is subtly wrong here: `$` also matches immediately before a "\n", so a
 * value like "cmul1234abcd\r\nBcc: x@y.example" would match and quietly return
 * the leading token. Scanning lines and validating the remainder of that line
 * rejects the whole malformed header instead.
 *
 * Rejects anything that is not a plain cuid-ish token, so a hostile header can
 * never inject a lookup that we would then trust.
 */
export function parseWarmupHeader(headers: string): string | null {
  for (const rawLine of headers.split(/\r\n|\r|\n/)) {
    const idx = rawLine.indexOf(":");
    if (idx === -1) continue;
    if (rawLine.slice(0, idx).trim().toLowerCase() !== WARMUP_HEADER.toLowerCase()) continue;
    const value = rawLine.slice(idx + 1).trim();
    // cuid / nanoid safe charset only -- blocks quotes, brackets, spaces, CRLF.
    if (!/^[A-Za-z0-9_-]{8,64}$/.test(value)) return null;
    return value;
  }
  return null;
}

/**
 * Extract a Message-ID from raw IMAP headers for cross-checking a match.
 * Same line-by-line approach as {@link parseWarmupHeader}.
 */
export function parseMessageIdHeader(headers: string): string | null {
  for (const rawLine of headers.split(/\r\n|\r|\n/)) {
    const idx = rawLine.indexOf(":");
    if (idx === -1) continue;
    if (rawLine.slice(0, idx).trim().toLowerCase() !== "message-id") continue;
    return rawLine.slice(idx + 1).trim();
  }
  return null;
}