-- MAILBOX WARM-UP (2026-10-02)
--
-- PURELY ADDITIVE. This migration creates new tables and adds new columns. It
-- contains no DROP, no DELETE, no TRUNCATE, no RENAME, no ALTER COLUMN, and no
-- data UPDATE. Existing campaigns, leads, templates and DailySendCounter rows
-- are not read, written or rewritten.
--
-- SAFETY: every added column is either nullable or carries a constant DEFAULT,
-- so existing rows pick up safe values:
--   SendSettings.warmupEnabled = false  -> warm-up is OFF for everyone after
--     this migration. Nothing starts sending until an operator explicitly
--     enables a mailbox.
--   SmtpAccount.imapStatus = 'unconfigured' -> existing mailboxes have no IMAP
--     config, so they can send warm-up but cannot have deliveries confirmed.
--
-- NOTE: warm-up does NOT raise campaign volume. DailySendCounter remains the
-- single shared per-mailbox daily ceiling for BOTH campaign and warm-up sends.
--
-- The statements below were generated by:
--   prisma migrate diff --from-schema-datasource prisma/schema.prisma \
--     --to-schema-datamodel prisma/schema.prisma --script
-- AlterTable
ALTER TABLE "SendSettings" ADD COLUMN     "warmupDailyIncrease" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "warmupEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "warmupMaxDelaySeconds" INTEGER NOT NULL DEFAULT 120,
ADD COLUMN     "warmupMaximumDailyVolume" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "warmupMinDelaySeconds" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "warmupStartingDailyVolume" INTEGER NOT NULL DEFAULT 5;

-- AlterTable
ALTER TABLE "SmtpAccount" ADD COLUMN     "imapHost" TEXT,
ADD COLUMN     "imapLastTestError" TEXT,
ADD COLUMN     "imapLastTestedAt" TIMESTAMP(3),
ADD COLUMN     "imapPasswordEncrypted" TEXT,
ADD COLUMN     "imapPort" INTEGER NOT NULL DEFAULT 993,
ADD COLUMN     "imapSecurity" TEXT NOT NULL DEFAULT 'ssl',
ADD COLUMN     "imapStatus" TEXT NOT NULL DEFAULT 'unconfigured',
ADD COLUMN     "imapUsernameEncrypted" TEXT;

-- CreateTable
CREATE TABLE "WarmupMailboxSettings" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "smtpAccountId" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "startingDailyVolume" INTEGER NOT NULL DEFAULT 5,
    "maximumDailyVolume" INTEGER NOT NULL DEFAULT 15,
    "dailyIncrease" INTEGER NOT NULL DEFAULT 1,
    "minimumDelaySeconds" INTEGER NOT NULL DEFAULT 60,
    "maximumDelaySeconds" INTEGER NOT NULL DEFAULT 120,
    "warmupWindowStart" TEXT NOT NULL DEFAULT '09:00',
    "warmupWindowEnd" TEXT NOT NULL DEFAULT '17:00',
    "pauseOnError" BOOLEAN NOT NULL DEFAULT true,
    "maxConsecutiveFailures" INTEGER NOT NULL DEFAULT 3,
    "status" TEXT NOT NULL DEFAULT 'paused',
    "statusMessage" TEXT,
    "consecutiveSuccessfulDays" INTEGER NOT NULL DEFAULT 0,
    "consecutiveFailures" INTEGER NOT NULL DEFAULT 0,
    "currentDay" INTEGER NOT NULL DEFAULT 0,
    "lastActiveDate" TEXT,
    "lastSendAt" TIMESTAMP(3),
    "startedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WarmupMailboxSettings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WarmupJob" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "mailboxId" TEXT NOT NULL,
    "senderSmtpAccountId" TEXT NOT NULL,
    "receiverSmtpAccountId" TEXT NOT NULL,
    "messageId" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'queued',
    "scheduledFor" TIMESTAMP(3) NOT NULL,
    "claimedAt" TIMESTAMP(3),
    "leaseExpiresAt" TIMESTAMP(3),
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "sentAt" TIMESTAMP(3),
    "deliveredAt" TIMESTAMP(3),
    "deliveryLatencyMs" INTEGER,
    "receiverMessageId" TEXT,
    "lastError" TEXT,
    "failureKind" TEXT,
    "permanentError" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WarmupJob_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WarmupEvent" (
    "id" TEXT NOT NULL,
    "jobId" TEXT,
    "mailboxId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "message" TEXT,
    "meta" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WarmupEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WarmupDailyUsage" (
    "id" TEXT NOT NULL,
    "mailboxId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "date" TEXT NOT NULL,
    "warmupSent" INTEGER NOT NULL DEFAULT 0,
    "warmupFailed" INTEGER NOT NULL DEFAULT 0,
    "delivered" INTEGER NOT NULL DEFAULT 0,
    "target" INTEGER NOT NULL DEFAULT 0,
    "rampDay" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WarmupDailyUsage_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "WarmupMailboxSettings_smtpAccountId_key" ON "WarmupMailboxSettings"("smtpAccountId");

-- CreateIndex
CREATE INDEX "WarmupMailboxSettings_userId_status_idx" ON "WarmupMailboxSettings"("userId", "status");

-- CreateIndex
CREATE INDEX "WarmupMailboxSettings_status_idx" ON "WarmupMailboxSettings"("status");

-- CreateIndex
CREATE UNIQUE INDEX "WarmupJob_messageId_key" ON "WarmupJob"("messageId");

-- CreateIndex
CREATE INDEX "WarmupJob_status_scheduledFor_idx" ON "WarmupJob"("status", "scheduledFor");

-- CreateIndex
CREATE INDEX "WarmupJob_mailboxId_status_idx" ON "WarmupJob"("mailboxId", "status");

-- CreateIndex
CREATE INDEX "WarmupJob_userId_createdAt_idx" ON "WarmupJob"("userId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "WarmupJob_mailboxId_scheduledFor_key" ON "WarmupJob"("mailboxId", "scheduledFor");

-- CreateIndex
CREATE INDEX "WarmupEvent_mailboxId_createdAt_idx" ON "WarmupEvent"("mailboxId", "createdAt");

-- CreateIndex
CREATE INDEX "WarmupEvent_userId_createdAt_idx" ON "WarmupEvent"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "WarmupEvent_type_idx" ON "WarmupEvent"("type");

-- CreateIndex
CREATE INDEX "WarmupDailyUsage_userId_date_idx" ON "WarmupDailyUsage"("userId", "date");

-- CreateIndex
CREATE UNIQUE INDEX "WarmupDailyUsage_mailboxId_date_key" ON "WarmupDailyUsage"("mailboxId", "date");

-- AddForeignKey
ALTER TABLE "WarmupMailboxSettings" ADD CONSTRAINT "WarmupMailboxSettings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WarmupMailboxSettings" ADD CONSTRAINT "WarmupMailboxSettings_smtpAccountId_fkey" FOREIGN KEY ("smtpAccountId") REFERENCES "SmtpAccount"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WarmupJob" ADD CONSTRAINT "WarmupJob_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WarmupJob" ADD CONSTRAINT "WarmupJob_mailboxId_fkey" FOREIGN KEY ("mailboxId") REFERENCES "WarmupMailboxSettings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WarmupJob" ADD CONSTRAINT "WarmupJob_senderSmtpAccountId_fkey" FOREIGN KEY ("senderSmtpAccountId") REFERENCES "SmtpAccount"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WarmupJob" ADD CONSTRAINT "WarmupJob_receiverSmtpAccountId_fkey" FOREIGN KEY ("receiverSmtpAccountId") REFERENCES "SmtpAccount"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WarmupEvent" ADD CONSTRAINT "WarmupEvent_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "WarmupJob"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WarmupEvent" ADD CONSTRAINT "WarmupEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WarmupDailyUsage" ADD CONSTRAINT "WarmupDailyUsage_mailboxId_fkey" FOREIGN KEY ("mailboxId") REFERENCES "WarmupMailboxSettings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WarmupDailyUsage" ADD CONSTRAINT "WarmupDailyUsage_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
