-- EMAIL VERIFICATION (2026-10-06)
--
-- PURELY ADDITIVE. This migration creates two new tables and adds one new
-- column. It contains no DROP, no DELETE, no TRUNCATE, no RENAME, no ALTER
-- COLUMN, and no data UPDATE.
--
-- SAFETY: every added column is nullable or carries a constant DEFAULT, so
-- existing rows pick up safe values:
--   Campaign.verificationPolicy = 'OFF' -> every existing campaign keeps its
--     exact previous send behaviour (no verification check at send time);
--     policies are the operator's choice per campaign afterwards.
--
-- The statements were generated by hand following the conventions of
-- prisma migrate diff (see 20261002120000_add_mailbox_warmup).

-- AlterTable
ALTER TABLE "Campaign"
ADD COLUMN "verificationPolicy" TEXT NOT NULL DEFAULT 'OFF';

-- CreateTable
CREATE TABLE "EmailVerification" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "normalizedEmail" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "confidence" INTEGER NOT NULL DEFAULT 0,
    "syntaxValid" BOOLEAN NOT NULL DEFAULT false,
    "domainValid" BOOLEAN NOT NULL DEFAULT false,
    "mxValid" BOOLEAN NOT NULL DEFAULT false,
    "smtpReachable" BOOLEAN NOT NULL DEFAULT false,
    "catchAll" BOOLEAN NOT NULL DEFAULT false,
    "disposable" BOOLEAN NOT NULL DEFAULT false,
    "roleAccount" BOOLEAN NOT NULL DEFAULT false,
    "freeProvider" BOOLEAN NOT NULL DEFAULT false,
    "provider" TEXT NOT NULL DEFAULT 'aftership',
    "typoSuggestion" TEXT,
    "errorCode" TEXT,
    "errorMessage" TEXT,
    "verificationVersion" TEXT NOT NULL,
    "checkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EmailVerification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VerificationJob" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "normalizedEmail" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'queued',
    "force" BOOLEAN NOT NULL DEFAULT false,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "nextAttemptAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "leaseExpiresAt" TIMESTAMP(3),
    "lastError" TEXT,
    "verificationId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VerificationJob_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "EmailVerification_userId_normalizedEmail_key" ON "EmailVerification"("userId", "normalizedEmail");

-- CreateIndex
CREATE INDEX "EmailVerification_userId_status_idx" ON "EmailVerification"("userId", "status");

-- CreateIndex
CREATE INDEX "EmailVerification_status_idx" ON "EmailVerification"("status");

-- CreateIndex
CREATE INDEX "EmailVerification_checkedAt_idx" ON "EmailVerification"("checkedAt");

-- CreateIndex
CREATE INDEX "EmailVerification_expiresAt_idx" ON "EmailVerification"("expiresAt");

-- CreateIndex
CREATE INDEX "VerificationJob_status_nextAttemptAt_idx" ON "VerificationJob"("status", "nextAttemptAt");

-- CreateIndex
CREATE INDEX "VerificationJob_userId_status_idx" ON "VerificationJob"("userId", "status");

-- CreateIndex
CREATE INDEX "VerificationJob_userId_createdAt_idx" ON "VerificationJob"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "VerificationJob_verificationId_idx" ON "VerificationJob"("verificationId");

-- AddForeignKey
ALTER TABLE "EmailVerification" ADD CONSTRAINT "EmailVerification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VerificationJob" ADD CONSTRAINT "VerificationJob_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VerificationJob" ADD CONSTRAINT "VerificationJob_verificationId_fkey" FOREIGN KEY ("verificationId") REFERENCES "EmailVerification"("id") ON DELETE SET NULL ON UPDATE CASCADE;